# Generated by Django 5.1.7 on 2025-03-18 23:56

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_type",
                    models.CharField(
                        choices=[
                            ("athlete", "Atleta"),
                            ("analyst", "Analista de Moda"),
                            ("enthusiast", "Entusiasta de Tênis"),
                            ("admin", "Administrador"),
                        ],
                        default="athlete",
                        max_length=20,
                    ),
                ),
                ("bio", models.TextField(blank=True, null=True)),
                ("location", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "shoe_size",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=3, null=True
                    ),
                ),
                ("preferred_brands", models.JSONField(default=list)),
                (
                    "style_preferences",
                    models.JSONField(
                        default=dict,
                        help_text="Preferências de estilo e personalização",
                    ),
                ),
                (
                    "fashion_specialization",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("experience_years", models.IntegerField(default=0)),
                ("profile_version", models.PositiveIntegerField(default=1)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "historical_data",
                    models.JSONField(
                        default=list, help_text="Histórico de alterações do perfil"
                    ),
                ),
                (
                    "compatibility_scores",
                    models.JSONField(
                        default=dict,
                        help_text="Scores de compatibilidade com outros usuários",
                    ),
                ),
            ],
            options={
                "verbose_name": "Perfil Consolidado",
                "verbose_name_plural": "Perfis Consolidados",
            },
        ),
    ]
