# Generated by Django 5.0 on 2025-01-28 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bio", models.TextField(blank=True, max_length=500)),
                ("birth_date", models.DateField(blank=True, null=True)),
                (
                    "avatar",
                    models.ImageField(blank=True, null=True, upload_to="avatars/"),
                ),
                ("age_min", models.IntegerField(default=18)),
                ("age_max", models.IntegerField(default=50)),
                ("location_preference", models.CharField(blank=True, max_length=100)),
                (
                    "preferred_brands",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Nike", "Nike"),
                            ("Adidas", "Adidas"),
                            ("Puma", "Puma"),
                            ("Asics", "Asics"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "preferred_styles",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Corrida", "Corrida"),
                            ("Casual", "Casual"),
                            ("Tênis", "Tênis"),
                            ("Basquete", "Basquete"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "preferred_colors",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Branco", "Branco"),
                            ("Azul", "Azul"),
                            ("Preto", "Preto"),
                            ("Vermelho", "Vermelho"),
                        ],
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
