# Generated by Django 5.0 on 2025-01-27 12:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="preferred_brands",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Nike", "Nike"),
                    ("Adidas", "Adidas"),
                    ("Puma", "Puma"),
                    ("Asics", "Asics"),
                ],
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="preferred_colors",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Branco", "Branco"),
                    ("Azul", "Azul"),
                    ("Preto", "Preto"),
                    ("Vermelho", "Vermelho"),
                ],
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="preferred_styles",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Corrida", "Corrida"),
                    ("Casual", "Casual"),
                    ("Tênis", "Tênis"),
                    ("Basquete", "Basquete"),
                ],
                max_length=100,
            ),
        ),
    ]
