# Generated by Django 5.0 on 2025-03-12 20:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_type",
                    models.CharField(
                        choices=[
                            ("athlete", "Atleta"),
                            ("analyst", "Analista de Moda"),
                            ("enthusiast", "Entusiasta de Tênis"),
                            ("admin", "Administrador"),
                        ],
                        default="athlete",
                        max_length=20,
                    ),
                ),
                ("bio", models.TextField(blank=True, null=True)),
                ("location", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "shoe_size",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=3, null=True
                    ),
                ),
                ("preferred_brands", models.JSONField(default=list)),
                (
                    "style_preferences",
                    models.JSONField(
                        default=dict,
                        help_text="Preferências de estilo e personalização",
                    ),
                ),
                (
                    "fashion_specialization",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("experience_years", models.IntegerField(default=0)),
                ("profile_version", models.PositiveIntegerField(default=1)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "historical_data",
                    models.JSONField(
                        default=list, help_text="Histórico de alterações do perfil"
                    ),
                ),
                (
                    "compatibility_scores",
                    models.JSONField(
                        default=dict,
                        help_text="Scores de compatibilidade com outros usuários",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Perfil Consolidado",
                "verbose_name_plural": "Perfis Consolidados",
            },
        ),
        migrations.DeleteModel(
            name="Profile",
        ),
        migrations.AddIndex(
            model_name="userprofile",
            index=models.Index(
                fields=["user_type"], name="profiles_us_user_ty_2e8a58_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userprofile",
            index=models.Index(
                fields=["shoe_size"], name="profiles_us_shoe_si_e0a5d9_idx"
            ),
        ),
    ]
