# Generated by Django 5.0 on 2025-03-20 01:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0013_historical_profiles"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userprofile",
            options={},
        ),
        migrations.RemoveIndex(
            model_name="userprofile",
            name="profiles_us_user_ty_2e8a58_idx",
        ),
        migrations.RemoveIndex(
            model_name="userprofile",
            name="profiles_us_shoe_si_e0a5d9_idx",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="historical_data",
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="compatibility_scores",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="experience_years",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="shoe_size",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=4, null=True
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="style_preferences",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("athlete", "Atleta"),
                    ("fashion", "Moda"),
                    ("casual", "Casual"),
                ],
                default="casual",
                max_length=20,
            ),
        ),
    ]
