# Generated by Django 5.1.7 on 2025-03-18 23:56

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("compatibility_score", models.FloatField()),
                ("matched_at", models.DateTimeField(auto_now_add=True)),
                ("is_mutual", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "matches",
            },
        ),
        migrations.CreateModel(
            name="MatchFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        choices=[
                            (1, "Muito Ruim"),
                            (2, "Ruim"),
                            (3, "Regular"),
                            (4, "Bom"),
                            (5, "Muito Bom"),
                        ]
                    ),
                ),
                ("feedback_text", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="SneakerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand", models.CharField(max_length=100)),
                (
                    "style",
                    models.CharField(
                        choices=[
                            ("ESP", "Esportivo"),
                            ("CAS", "Casual"),
                            ("VIN", "Vintage"),
                            ("SOC", "Social"),
                            ("FAS", "Fashion"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("BLK", "Preto"),
                            ("WHT", "Branco"),
                            ("COL", "Colorido"),
                            ("NEU", "Neutro"),
                        ],
                        max_length=3,
                    ),
                ),
                ("price_range", models.IntegerField()),
                ("occasion", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "sneaker_profiles",
            },
        ),
    ]
