# Generated by Django 5.0 on 2025-01-28 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("compatibility_score", models.FloatField()),
                ("matched_at", models.DateTimeField(auto_now_add=True)),
                ("is_mutual", models.BooleanField(default=False)),
                (
                    "user_a",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches_as_a",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user_b",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches_as_b",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "matches",
                "unique_together": {("user_a", "user_b")},
            },
        ),
        migrations.CreateModel(
            name="SneakerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand", models.CharField(max_length=100)),
                (
                    "style",
                    models.CharField(
                        choices=[
                            ("ESP", "Esportivo"),
                            ("CAS", "Casual"),
                            ("VIN", "Vintage"),
                            ("SOC", "Social"),
                            ("FAS", "Fashion"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("BLK", "Preto"),
                            ("WHT", "Branco"),
                            ("COL", "Colorido"),
                            ("NEU", "Neutro"),
                        ],
                        max_length=3,
                    ),
                ),
                ("price_range", models.IntegerField()),
                ("occasion", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "sneaker_profiles",
            },
        ),
        migrations.CreateModel(
            name="MatchFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        choices=[
                            (1, "Muito Ruim"),
                            (2, "Ruim"),
                            (3, "Regular"),
                            (4, "Bom"),
                            (5, "Muito Bom"),
                        ]
                    ),
                ),
                ("feedback_text", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="matching.match"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "match")},
            },
        ),
    ]
