# Generated by Django 5.0 on 2025-01-26 02:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="premium_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
