# Generated by Django 5.0 on 2025-03-19 23:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_approved",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("GERENTE", "Gerente"), ("ANALISTA", "Analista")],
                db_index=True,
                default="ANALISTA",
                max_length=10,
            ),
        ),
    ]
