# Generated by Django 5.0 on 2025-01-28 13:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("GERENTE", "Gerente"), ("ANALISTA", "Analista")],
                default="ANALISTA",
                max_length=10,
            ),
        ),
    ]
