# Generated by Django 5.1.7 on 2025-03-18 23:56

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AIModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("version", models.CharField(max_length=20)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Rascunho"),
                            ("review", "Em Revisão"),
                            ("approved", "Aprovado"),
                            ("rejected", "Rejeitado"),
                        ],
                        max_length=20,
                    ),
                ),
                ("metrics", models.JSONField(blank=True, null=True)),
                (
                    "training_status",
                    models.CharField(
                        choices=[
                            ("queued", "Na Fila"),
                            ("processing", "Processando"),
                            ("completed", "Concluído"),
                            ("failed", "Falhou"),
                        ],
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("training_progress", models.FloatField(default=0)),
                (
                    "training_message",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("training_started_at", models.DateTimeField(blank=True, null=True)),
                ("training_completed_at", models.DateTimeField(blank=True, null=True)),
                ("review_notes", models.TextField(blank=True, null=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ColumnMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mapping", models.JSONField(default=dict)),
                ("is_validated", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Dataset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("file", models.FileField(upload_to="datasets/")),
                ("records_count", models.IntegerField(default=0)),
                ("is_processed", models.BooleanField(default=False)),
                (
                    "dataset_type",
                    models.CharField(
                        choices=[("upload", "Upload"), ("generated", "Gerado")],
                        default="upload",
                        max_length=20,
                    ),
                ),
                ("file_size", models.BigIntegerField(default=0)),
                (
                    "file_type",
                    models.CharField(
                        choices=[("csv", "CSV"), ("json", "JSON"), ("xlsx", "Excel")],
                        default="csv",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("processing", "Processando"),
                            ("mapping", "Aguardando Mapeamento"),
                            ("ready", "Pronto"),
                        ],
                        default="processing",
                        max_length=20,
                    ),
                ),
                ("stats", models.JSONField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Dataset",
                "verbose_name_plural": "Datasets",
            },
        ),
    ]
