# Generated by Django 5.0 on 2025-03-21 13:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenis_admin", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="aimodel",
            name="model_file",
            field=models.FileField(blank=True, null=True, upload_to="models/"),
        ),
    ]
