# Generated by Django 5.0 on 2025-01-29 23:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenis_admin", "0004_dataset_file_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="aimodel",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
