# Generated by Django 5.0 on 2025-01-30 00:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenis_admin", "0005_aimodel_updated_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="aimodel",
            options={},
        ),
        migrations.RemoveField(
            model_name="aimodel",
            name="model_file",
        ),
        migrations.RemoveField(
            model_name="aimodel",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="dataset",
            name="file_type",
        ),
        migrations.AlterField(
            model_name="aimodel",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="aimodel",
            name="dataset",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tenis_admin.dataset"
            ),
        ),
        migrations.AlterField(
            model_name="dataset",
            name="status",
            field=models.CharField(
                choices=[
                    ("processing", "Processando"),
                    ("mapping", "Aguardando Mapeamento"),
                    ("ready", "Pronto"),
                ],
                default="processing",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="ColumnMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mapping", models.JSONField(default=dict)),
                ("is_validated", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "dataset",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="column_mapping",
                        to="tenis_admin.dataset",
                    ),
                ),
            ],
        ),
    ]
