# Generated by Django 5.0 on 2025-02-27 03:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenis_admin", "0007_dataset_file_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="aimodel",
            name="training_completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="aimodel",
            name="training_message",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="aimodel",
            name="training_progress",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="aimodel",
            name="training_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="aimodel",
            name="training_status",
            field=models.CharField(
                choices=[
                    ("queued", "Na Fila"),
                    ("processing", "Processando"),
                    ("completed", "Concluído"),
                    ("failed", "Falhou"),
                ],
                default="queued",
                max_length=20,
            ),
        ),
    ]
